name: Java CI for Selenium

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: latest

      - name: Verify Chrome installation
        run: chrome --version

      - name: Build with Maven
        working-directory: KredSafe_TestAutomation
        run: mvn clean install -DskipTests

      - name: Run Selenium tests
        working-directory: KredSafe_TestAutomation
        run: mvn test

