name: Java CI with manual TestNG

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Create lib folder and download TestNG
        run: |
          mkdir lib
          curl -L -o lib/testng.jar https://repo1.maven.org/maven2/org/testng/testng/7.9.0/testng-7.9.0.jar

      - name: Compile code manually using testng.jar
        working-directory: KredSafe_TestAutomation
        run: |
          mkdir -p target/classes
          javac -cp "lib/testng.jar" -d target/classes $(find src/main/java -name "*.java")

      - name: Run tests manually using testng
        working-directory: KredSafe_TestAutomation
        run: |
          java -cp "lib/testng.jar;target/classes" org.testng.TestNG testng.xml


